# https://github.com/erebe/wstunnel
# https://github.com/erebe/wstunnel/blob/main/Dockerfile

FROM debian:trixie-slim AS final-image

RUN useradd -ms /bin/bash app && \
        apt-get update && \
        apt-get -y upgrade && \
        apt install -y --no-install-recommends ca-certificates dumb-init && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists

WORKDIR /home/app

ENV RUST_LOG="INFO"

USER app

ENTRYPOINT ["/usr/bin/dumb-init", "-v", "--"]
CMD ["/bin/sh", "-c", "exec /home/app/wstunnel server $(tr '\n' ' ' < /home/app/WsServerConfig)"]
